# Generated by Django 3.2 on 2024-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('otp', models.IntegerField()),
                ('created_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'email_verifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('postid', models.IntegerField()),
                ('uid', models.IntegerField()),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('postid', models.IntegerField()),
                ('amount', models.CharField(max_length=255)),
                ('paidtime', models.DateTimeField(blank=True, null=True)),
                ('transictionid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('relation', models.CharField(max_length=255)),
                ('approvedstatus', models.IntegerField()),
                ('pnumber', models.CharField(max_length=255)),
                ('targetamount', models.IntegerField()),
                ('targateddate', models.DateTimeField()),
                ('catagory', models.CharField(max_length=255)),
                ('collectedamount', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('citizenship', models.TextField()),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('photos', models.TextField(blank=True, null=True)),
                ('officialdocs', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('email_verified_at', models.DateTimeField()),
                ('is_verified', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('role', models.IntegerField()),
                ('pnumber', models.BigIntegerField(blank=True, null=True)),
                ('mname', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
